---
vatz_protocol_info:
  protocol_identifier: "near"
  port: 9090
  notification_info:
    discord_secret: "XXXXX"
    pager_duty_secret: "YYYYY"
plugins_infos:
  default_verify_interval:  15
  default_execute_interval: 30
  default_plugin_name: "vatz-plugin"
  plugins:
    - plugin_name: "vatz-plugin-near-node-check"
      plugin_address: "localhost"
      plugin_port: 9091
      executable_methods:
        - method_name: "isUp"
        - method_name: "getBlockHeight"
        - method_name: "getNumberOfPeers"