---
vatz_protocol_info:
  protocol_identifier: "near"
  port: 9090
plugins_info:
  plugin_name: "near"
  plugin_port: 9091
  default_verify_interval: 60
  default_execute_interval: 30
  executable_apis:
    - method_name: "default_check_function"
      api_interval: 45
