---
vatz_protocol_info:
  protocol_identifier: "VATZ"
  port: 9090
  notification_info:
    discord_secret: "xxxxxxx"
    pager_duty_secret: "YYYYY"
  health_checker_schedule:
    - "* 1t * * *"
plugins_infos:
  default_verify_interval: 15
  default_execute_interval: 30
  default_plugin_name: "vatz-plugin"
  plugins:
    - plugin_name: "sample1"
      plugin_address: "localhost"
      plugin_port: 9091
      executable_methods:
        - method_name: "sampleMethod1"
    - plugin_name: "sample2"
      plugin_address: "localhost"
      verify_interval: 7
      execute_interval: 9
      plugin_port: 10002
      executable_methods:
        - method_name: "sampleMethod2"