---
vatz_protocol_info:
  protocol_identifier: "near"
  port: 9090
  discord_secret: "https://discord.com/api/webhooks/955326233057566750/e-Tkq6mvxXYsx3Rqi3ttxDes76UXPpgk76Bnz5jF8_DwWgdNF-iNf7ZWdqi1nQnHO-zC"
plugins_info:
  plugin_name: "near"
  plugin_port: 9091
  default_verify_interval: 60
  default_execute_interval: 30
  executable_apis:
    - method_name: "default_check_function"
      api_interval: 45
