name: Coverage Test

on:
  pull_request_target:
    types: [opened, synchronize]
  push:
    branches:
      - main

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.5
      - name: Build Code
        run: |
          make build
      - name: Run coverage test
        run: |
          make coverage
      - name: Deny PR on test failure
        if: failure()
        run: |
          echo "Coverage test failed. This PR cannot be merged."
          exit 1
