name: Coverage Test

on:
  pull_request_target:
    types: [opened, synchronize]

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}  # Check out the source branch of the PR
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.5
      - name: Build Code
        run: |
          make build
      - name: Run coverage test
        run: |
          make coverage
      - name: Deny PR on test failure
        if: failure()
        run: |
          echo "Coverage test failed. This PR cannot be merged."
          exit 1
