name: Notify PR has raised
on:
  pull_request:
    types: [opened, reopened]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get pull request details
        id: pr
        run: |
          PR_NUMBER=${{ github.event.number }}
          PR=$(curl -s -H https://api.github.com/repos/xellos00/pulls/$PR_NUMBER)
          PR_TITLE=$(echo $PR | jq -r '.title')
          PR_URL=$(echo $PR | jq -r '.html_url')
          PR_USER=$(echo $PR | jq -r '.user.login')
          PR_BODY=$(echo $PR | jq -r '.body')
      - name: Discord Webhook Action
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          content: |
            A new pull request has been opened by @$PR_USER:
            - [$PR_TITLE]($PR_URL)
            $PR_BODY

      - name: Notify
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: "A new pull request has been opened by @$PR_USER: \n
                  - [$PR_TITLE]($PR_URL) \n
                    $PR_BODY "