name: Notify PR has raised
on:
  pull_request:
    types: [opened, reopened]
env:
  PR_TITLE: "N/A"
  PR_URL: "N/A"
  PR_USER: "N/A"
  PR_BODY: "N/A"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get pull request details
        id: pr
        run: |
          PR_NUMBER=${{ github.event.number }}
          curl -s \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/xellos00/vatz/$PR_NUMBER >> new_pull.json
          echo "PR_TITLE=$(cat new_pull.json | jq -r '.title')" >> "$GITHUB_ENV"
          echo "PR_URL=$(cat new_pull.json | jq -r '.html_url')" >> "$GITHUB_ENV"
          echo "PR_USER=$(cat new_pull.json | jq -r '.user.login')" >> "$GITHUB_ENV"
          echo "PR_BODY=$(cat new_pull.json | jq -r '.body')" >> "$GITHUB_ENV"
      - name: Notify
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: "A new pull request has been opened by ${{ env.PR_USER }} : \n
                  - [${{ env.PR_TITLE }}](${{ env.PR_URL }}) \n
                    ${{ env.PR_BODY }} "